ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/nginx/default, ansible/roles/common/templates/nginx/index.html
This sets up the vm hostname and a default page for nginx that links to the right url.
closes https://github.com/liquidinvestigations/liquidinvestigations/issues/35
=> Default nginx page

Readme.md, ansible/roles/devel/tasks/main.yml
* set up a password for the liquid user
* permit the liquid user to use sudo
* permit password auth for sshd
=> make logging in easier during development

bin/build-odroid_c2-image.sh, bin/build-x86_64-image.sh
The goal is to bring the odroid build script up-to-date and eventually merge it with the x86 script.
=> Refactor build scripts

ansible/roles/davros/files/authproxy/authproxy.py, ansible/roles/davros/files/authproxy/requirements.txt, ansible/roles/davros/files/supervisor/davros.conf, ansible/roles/davros/tasks/authproxy.yml, ansible/roles/davros/tasks/main.yml, ansible/roles/davros/templates/authproxy/config/basename.py, ansible/roles/davros/templates/nginx/davros.conf
Here's a quick-and-dirty OAuth2 client implementation as reverse proxy in front of Davros. It doesn't handle logouts at the moment.
=> Reverse proxy for Davros OAuth

bin/install
This PR also adds a bit of functionality: if ansible is not installed, it will add the PPA, and install ansible, *then* run it.
=> rewrite bin/install in python3

ansible/roles/common/files/libexec/firewall, ansible/roles/common/tasks/main.yml
Closes https://github.com/liquidinvestigations/liquidinvestigations/issues/81
=> Firewall script

ansible/roles/davros/tasks/main.yml, ansible/roles/davros/templates/initialize.d/davros.sh, ansible/roles/hoover/templates/initialize.d/hoover.sh, ansible/roles/liquid-core/templates/initialize.d/liquid-core.sh, ansible/roles/liquid-core/templates/libexec/create-oauth-application
* rewrite in python3
* move the django code to the liquid-core project as management command
Closes https://github.com/liquidinvestigations/liquidinvestigations/issues/91; depends on https://github.com/liquidinvestigations/core/pull/6
=> Clean up `create-oauth-application`

ansible/roles/common/tasks/main.yml, ansible/roles/davros/tasks/main.yml, ansible/roles/devel/tasks/main.yml, ansible/roles/hoover/tasks/main.yml, ansible/roles/hotspot/tasks/main.yml, ansible/roles/hypothesis/tasks/client.yml, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/liquid-core/tasks/main.yml, ansible/roles/matrix/tasks/main.yml, ansible/roles/node6/tasks/main.yml
fixes https://github.com/liquidinvestigations/setup/issues/11
=> stick to a coding style

ansible/roles/liquid-core/tasks/main.yml, ansible/roles/liquid-core/templates/initialize.d/liquid-core.sh
closes https://github.com/liquidinvestigations/liquidinvestigations/issues/87
=> move database migration to first boot

ansible/roles/common/files/initialize.d/common, ansible/roles/common/tasks/main.yml, ansible/roles/devel/tasks/main.yml, py/images/demo.py
* set up ssh in `common` role
* enable sshd only with `devel` role
* generate server keys on boot
Closes #39
=> Fixes for sshd

Readme.md, py/images/demo.py
* inject custom `config.yml` into ansible
* documentation on creating a demo image
* remove the hotfix for hoover ui
(part of https://github.com/liquidinvestigations/liquidinvestigations/issues/39)
=> Demo image docs and config

ansible/roles/dokuwiki/tasks/main.yml, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/liquid-core/tasks/main.yml, ansible/roles/matrix/files/hooks/user-created, ansible/roles/matrix/files/hooks/user-deleted, ansible/roles/matrix/files/hooks/user-passwd, ansible/roles/matrix/files/initialize.d/matrix, ansible/roles/matrix/tasks/main.yml, ansible/roles/matrix/templates/homeserver.yaml
Implement change password hook & rearrange some of the hooks code.
Closes https://github.com/liquidinvestigations/liquidinvestigations/issues/84
=> Fix matrix shared users

ansible/roles/common/files/initialize.d/common, ansible/roles/common/tasks/hooks.yml, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/boot.sh, ansible/roles/davros/files/supervisor/davros.conf, ansible/roles/davros/templates/initialize.d/davros.sh, ansible/roles/discover/files/initialize.d/discover.sh, ansible/roles/discover/templates/supervisor/discover.conf, ansible/roles/dokuwiki/files/initialize.d/dokuwiki, ansible/roles/dokuwiki/files/supervisor/dokuwiki.conf, ansible/roles/hoover/templates/initialize.d/hoover.sh, ansible/roles/hoover/templates/supervisor/hoover.conf, ansible/roles/hotspot/tasks/main.yml, ansible/roles/hypothesis/templates/initialize.d/hypothesis.sh, ansible/roles/liquid-core/tasks/main.yml, ansible/roles/liquid-core/templates/initialize.d/liquid-core-devel.sh, ansible/roles/liquid-core/templates/initialize.d/liquid-core.sh, ansible/roles/liquid-core/templates/supervisor/liquid-core.conf, ansible/roles/matrix/files/initialize.d/matrix, ansible/roles/matrix/files/supervisor/matrix.conf
Closes https://github.com/liquidinvestigations/setup/issues/33
Closes https://github.com/liquidinvestigations/liquidinvestigations/issues/108
=> Fix service boot order

ansible/roles/liquid-core/templates/initialize.d/liquid-core.sh
closes https://github.com/liquidinvestigations/setup/issues/49
=> fix grep call in liquid-core initialize

Jenkinsfile, Jenkinsfile.arm64, ansible/roles/common/tasks/main.yml, ansible/roles/devel/tasks/main.yml, ansible/roles/discover/tasks/main.yml, ansible/roles/docker/tasks/main.yml, ansible/roles/hoover/tasks/main.yml, ansible/roles/hotspot/tasks/main.yml, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/matrix/tasks/main.yml, ansible/roles/node6/tasks/main.yml, bin/install, prerequisites/Jenkinsfile, prerequisites/Jenkinsfile.arm64, py/images/builders/base.py, py/images/builders/cloud.py, py/images/builders/odroid.py, py/images/cmd.py, py/images/demo.py, py/images/setup.py
Speed up build times by pre-building a "preprequisites" image, which contains safe, rarely-changing material. For now that means APT packages, but we can add pip and npm packages too.
Closes #56.
=> Prerequisites

ansible/image_chroot.yml, ansible/roles/liquid-core/templates/nginx/liquid-core.conf, ansible/roles/web-ui/tasks/main.yml, ansible/server.yml, ansible/vars/defaults.yml, jenkins-config.yml
closes https://github.com/liquidinvestigations/setup/issues/51
=> install, build and serve web-ui

ansible/roles/common/tasks/main.yml
closes https://github.com/liquidinvestigations/liquidinvestigations/issues/132
=> disable ubuntu auto-upgrade

ansible/roles/hypothesis/templates/initialize.d/hypothesis.sh
fixes https://github.com/liquidinvestigations/setup/issues/4
=> set a temporary secret key for hypothesis init

ansible/roles/common/tasks/hooks.yml, ansible/roles/common/templates/boot.sh
=> remove unused `on-boot` hook; restart all services

ansible/roles/davros/tasks/main.yml, ansible/roles/dokuwiki/tasks/main.yml, ansible/roles/hoover/tasks/main.yml, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/liquid-core/templates/local.py, ansible/roles/matrix/tasks/main.yml, ansible/roles/network/tasks/vpn-client.yml, ansible/roles/network/tasks/vpn-server.yml, ansible/vars/defaults.yml, jenkins-config.yml
closes https://github.com/liquidinvestigations/setup/issues/69
=> Service enable disable

ansible/roles/common/files/initialize.d/install-templates, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/initialize.sh, ansible/roles/common/templates/options.json, ansible/vars/defaults.yml, bin/run_first_boot_tests.py, jenkins-config.yml, tests/install_browsers.sh, tests/testsuite/test_acceptance_with_browsers.py
Fixes https://github.com/liquidinvestigations/setup/issues/89.
=> Integrate facelift into the build

Jenkinsfile, Readme.md, ansible/roles/common/files/sudoers.d/liquid-hooks, ansible/roles/common/tasks/hooks.yml, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/initialize.sh, ansible/roles/davros/tasks/main.yml, ansible/roles/davros/templates/initialize.d/davros.sh, ansible/roles/discover/tasks/main.yml, ansible/roles/dokuwiki/tasks/main.yml, ansible/roles/hoover/tasks/main.yml, ansible/roles/hoover/templates/initialize.d/hoover.sh, ansible/roles/hoover/templates/initialize.d/import-davros-sync.sh, ansible/roles/hoover/templates/initialize.d/import-testdata.sh, ansible/roles/hoover/templates/supervisor/hoover.conf, ansible/roles/hypothesis/files/hooks/user, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/hypothesis/templates/initialize.d/hypothesis.sh, ansible/roles/hypothesis/templates/supervisor/hypothesis.conf, ansible/roles/liquid-core/tasks/main.yml, ansible/roles/liquid-core/templates/initialize.d/liquid-core-devel.sh, ansible/roles/liquid-core/templates/initialize.d/liquid-core.sh, ansible/roles/liquid-core/templates/supervisor/liquid-core.conf, ansible/roles/matrix/files/supervisor/matrix.conf, ansible/roles/matrix/tasks/main.yml, ansible/roles/web-ui/tasks/main.yml, bin/run_first_boot_tests.py, ci/prepare-image-for-testing
Ignore the branch name for now
=> Split liquid user into liquid-apps and liquid-admin

Jenkinsfile.noapps, tests/testsuite/test_acceptance_with_browsers.py, tests/testsuite/test_apps_respond_on_http.py
Except, of course, for the app-specific tests.
=> Run the test suite on the no-apps build

Jenkinsfile, bin/run_first_boot_tests.py
Mount the Jenkins setup dir in /opt/setup, over the existing installed one.
=> Run tests in /opt/setup

ansible/roles/hoover/tasks/main.yml, ansible/roles/hoover/templates/search-local.py, ansible/roles/hoover/templates/snoop-local.py, ansible/roles/liquid-core/templates/local.py
closes https://github.com/liquidinvestigations/setup/issues/106
=> Debug flag for apps

ansible/roles/hoover/tasks/main.yml
Fixes https://github.com/liquidinvestigations/liquidinvestigations/issues/241
=> keep our own mirror of tika

tests/testsuite/test_acceptance_with_browsers.py
closes https://github.com/liquidinvestigations/liquidinvestigations/issues/240
=> retry to create the splinter browser 3 times

Jenkinsfile.rock64, ansible/roles/common/tasks/main.yml
* Use the prerequisites image
* Force ansible version 2.4 (fixes #124)
=> Rock64 build

ansible/roles/common/tasks/sshd.yml, ansible/roles/davros/tasks/main.yml, ansible/roles/dokuwiki/tasks/main.yml, ansible/roles/hoover/tasks/main.yml, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/liquid-core/tasks/main.yml, ansible/roles/matrix/tasks/main.yml, ansible/roles/network/tasks/lan.yml, ansible/roles/network/tasks/vpn-client.yml, ansible/roles/network/tasks/vpn-server.yml, py/liquid/reconfigure.py
addresses https://github.com/liquidinvestigations/setup/issues/117, https://github.com/liquidinvestigations/liquidinvestigations/issues/238
=> Only reconfigure what we need

ansible/liquid.yml, ansible/roles/common/files/postgresql.conf, ansible/roles/common/tasks/main.yml, ansible/roles/dokuwiki/tasks/main.yml, ansible/roles/hoover/tasks/main.yml, ansible/roles/hoover/templates/elasticsearch-config/elasticsearch.yml, ansible/roles/hoover/templates/initialize.d/hoover.sh, ansible/roles/hypothesis/tasks/main.yml, ansible/roles/hypothesis/templates/elasticsearch-config/elasticsearch.yml, ansible/roles/hypothesis/templates/initialize.d/hypothesis.sh, ansible/roles/liquid-core/tasks/main.yml, ansible/roles/liquid-core/templates/first-boot.d/liquid-core.sh, ansible/roles/liquid-core/templates/local.py, ansible/roles/save-var-lib-liquid-template/tasks/main.yml
move app data files to `/var/lib/liquid`
=> Move all data to var

ansible/roles/davros/templates/authproxy/config/basename.py, ansible/roles/hoover/templates/search-local.py, ansible/roles/matrix/files/liquid_auth_provider.py, ansible/roles/matrix/files/supervisor/matrix.conf, ansible/roles/matrix/tasks/authproxy.yml, ansible/roles/matrix/tasks/main.yml, ansible/roles/matrix/templates/authproxy/settings.py, ansible/roles/matrix/templates/homeserver.yaml, ansible/roles/matrix/templates/initialize.d/authproxy.sh, ansible/roles/matrix/templates/nginx/matrix.conf, ansible/vars/defaults.yml, jenkins-config.yml, tests/testsuite/test_acceptance_with_browsers.py
All this spaghetti to pass around a lousy token. But it works! Except for logout: https://github.com/liquidinvestigations/liquidinvestigations/issues/303.
Addresses https://github.com/liquidinvestigations/liquidinvestigations/issues/279
=> Matrix sso

ansible/roles/hoover/files/libexec/snoop2-updater
Needs manual testing before we merge.
Closes https://github.com/liquidinvestigations/liquidinvestigations/issues/295
=> Fix davros-sync
